import { Inter } from "next/font/google";
import "./globals.css";
import SiteNavbar from "@/app/components/SiteNavbar";
import connectDB from "@/services/mongo";
import AuthProvider from "./providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eventry | Learn with Sumit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SiteNavbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
